version: "3"

services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql

networks:
  default:
    name: mariadb_net
    external: true
